### Find All Persons
GET http://localhost:8080/api/person

### Get Person by ID
GET http://localhost:8080/api/person/2


### Create new Person
POST http://localhost:8080/api/person
Content-Type: application/json

{
  "id": 1,
  "email": "harrypotter@mail.com",
  "name": "Harry",
  "surname": "Potter",
  "password": "harrypotter",
  "phone": "4444"
}

### Update existing Person with invalid id
PUT http://localhost:8080/api/person/2
Content-Type: application/json

{
  "id": 2,
  "email": "walterwhite@mail.com",
  "name": "Walter",
  "surname": "White",
  "password": "walterwhite",
  "phone": "66666"
}

### Delete by id
DELETE http://localhost:8080/api/person/1