### FIND ALL CARTS
GET http://localhost:8080/api/shopping-cart

### FIND CART BY ID
GET http://localhost:8080/api/shopping-cart/1

### CREATE NEW CART
POST http://localhost:8080/api/shopping-cart
Content-Type: application/json

{
  "id": "a276bcbb-1534-402c-8046-3510436072a7",
  "products": [
    {
      "productId": 4,
      "quantity": 1
    },
    {
      "productId": 5,
      "quantity": 2
    }
  ]
}

### Update existing Shopping Cart with invalid id
PUT http://localhost:8080/api/shopping-cart/a276bcbb-1534-402c-8046-3510436072a7
Content-Type: application/json

{
  "id": "a847e547-a345-4d03-84b0-26dd29342505",
  "products": [
    {
      "productId": 1,
      "quantity": 1
    },
    {
      "productId": 1,
      "quantity": 1
    }
  ]
}

### Delete by id
DELETE http://localhost:8080/api/shopping-cart/a276bcbb-1534-402c-8046-3510436072a7